language: julia

os:
  - linux

dist: bionic

julia:
  - 1.3
  - 1.4
  - nightly

env:
  global:
    - JULIA_MPI_BINARY=system
    # - JULIA_MPIEXEC_TEST_ARGS="--oversubscribe"  # useful for OpenMPI
    - JULIA_HDF5_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/hdf5/mpich

cache:
  directories:
    - $HOME/.julia/registries
    - $HOME/.julia/artifacts

script:
  # Force precompilation of packages in serial mode.
  # Otherwise, if precompilation runs in parallel, there may be race
  # conditions...
  # Also install and build HDF5.jl, and show version info.
  - julia --project=@. -e 'using Pkg;
                           using InteractiveUtils;
                           versioninfo();
                           pkg"add HDF5";
                           using HDF5;
                           @show HDF5.libhdf5;
                           pkg"instantiate";
                           pkg"precompile";
                           using MPI;
                           println("\n", MPI.MPI_LIBRARY_VERSION_STRING);'
  - julia --project=@. --color=yes -e 'import Pkg; Pkg.test(coverage=true)'

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

# https://docs.travis-ci.com/user/installing-dependencies/
before_install:
  - sudo apt-get -y install mpich libmpich-dev libhdf5-mpich-dev

after_success:
  - if [[ $TRAVIS_JULIA_VERSION == 1.4 ]]; then
      julia -e 'using Pkg;
                pkg"add Coverage";
                using Coverage;
                Codecov.submit(Codecov.process_folder());
                Coveralls.submit(Coveralls.process_folder());';
    fi

addons:
  apt:
    update: true  # runs apt-get update

notifications:
  email: false

# vim: shiftwidth=2
