name = "PencilFFTs"
uuid = "4a48f351-57a6-4416-9ec4-c37015456aae"
authors = ["Juan Ignacio Polanco <jipolanc@gmail.com>"]
version = "0.9.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
PencilArrays = "0e08944d-e94e-41b1-9406-dcf66b6a9d2e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
FFTW = "1"
MPI = "0.12, 0.13, 0.14, 0.15"
PencilArrays = "0.2, 0.3"
Reexport = "0.2"
TimerOutputs = "0.5"
julia = "1.3"
