[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
PencilFFTs = "4a48f351-57a6-4416-9ec4-c37015456aae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
