[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PencilFFTs = "4a48f351-57a6-4416-9ec4-c37015456aae"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
