[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
